# Typed signatures for the compiled `valgebra._valgebra` extension.
#
# This stub carries the *types* of the public surface for type checkers and IDEs.
# The prose documentation lives on the compiled objects themselves (the Rust
# docstrings) and is rendered on the API reference page, so it has a single
# source and cannot drift from a hand-copied duplicate here. Import the public
# names from the top-level `valgebra` package, not from this module.

from collections.abc import Callable

class ValidationError(Exception):
    # The structured, machine-readable error model. `errors` is a tuple of
    # per-failure items, each a JSON-serializable dict with the keys
    # `code`/`path`/`message`/`expected`/`value`; `json.dumps(err.errors)` is the
    # JSON output. The scalar attributes mirror the first item.
    code: str
    path: tuple[str | int, ...]
    message: str
    expected: str
    value: str
    errors: tuple[dict[str, object], ...]
    def __init__(self, message: str) -> None: ...

class Validator:
    def __init__(self, schema: object) -> None: ...
    def validate(self, obj: object, *, fail_fast: bool = ...) -> None: ...
    def is_valid(self, obj: object) -> bool: ...
    def ensure(self, obj: object) -> object: ...
    def validate_json(self, data: str | bytes, *, fail_fast: bool = ...) -> None: ...
    def load(self, data: str | bytes, *, fail_fast: bool = ...) -> object: ...
    def is_valid_json(self, data: str | bytes) -> bool: ...
    def open(self) -> Validator: ...
    def close(self) -> Validator: ...
    def simplify(self) -> Validator: ...
    def is_empty(self) -> bool: ...
    def is_subtype_of(self, other: object) -> bool: ...
    def is_equivalent(self, other: object) -> bool: ...
    def __contains__(self, obj: object) -> bool: ...
    def __or__(self, other: object) -> Validator: ...
    def __ror__(self, other: object) -> Validator: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __copy__(self) -> Validator: ...
    def __deepcopy__(self, memo: object) -> Validator: ...

def union(*schemas: object) -> Validator: ...
def intersection(*schemas: object) -> Validator: ...
def complement(schema: object) -> Validator: ...
def recursive(
    builder: Callable[[Validator], object],
) -> Validator: ...

anything: Validator
nothing: Validator

MAX_SCHEMA_DEPTH: int
MAX_DEFINITIONS: int
MAX_SCHEMA_NODES: int
