from collections.abc import Callable

class ValidationError(Exception):
    # The offending value's machine-readable failure: a stable `code`, the
    # `path` to the value, the `expected` label, a `value` summary, and the
    # rendered `message`.
    code: str
    path: tuple[str | int, ...]
    message: str
    expected: str
    value: str
    def __init__(self, message: str) -> None: ...

class CompiledValidator:
    def validate(self, obj: object) -> None: ...
    def is_valid(self, obj: object) -> bool: ...
    def cast(self, obj: object) -> object: ...

def validator(schema: object) -> CompiledValidator: ...
def union(*schemas: object) -> CompiledValidator: ...
def intersect(*schemas: object) -> CompiledValidator: ...
def complement(schema: object) -> CompiledValidator: ...
def fixed_sequence(*members: object) -> CompiledValidator: ...
def simplify(validator: CompiledValidator) -> CompiledValidator: ...
def lazy(
    builder: Callable[[CompiledValidator], object],
) -> CompiledValidator: ...

anything: CompiledValidator
nothing: CompiledValidator
